# Generated by Django 3.2 on 2023-10-24 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='用户编码')),
                ('name', models.CharField(max_length=128, verbose_name='用户中文名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('enabled', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='是否启用')),
            ],
        ),
        migrations.CreateModel(
            name='DevTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8d4b2cba-ee71-4515-a6bd-a0ec286ebefe'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('img', models.ImageField(blank=True, default='upload/none.png', upload_to='image')),
                ('device_type', models.CharField(blank=True, max_length=40)),
                ('is_custom_registered', models.BooleanField(default=False)),
                ('protocal_type', models.CharField(choices=[('MQTT', 'MQTT'), ('HTTP', 'HTTP'), ('CoAP', 'CoAP')], default='HTTP', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
