# Generated by Django 3.2 on 2023-10-24 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('309da039-4bb3-4189-8bf0-35c9f870d11c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
