# Generated by Django 3.2 on 2023-07-06 02:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20230706_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('728c9604-bcdb-43a3-b71e-8d777a19e67a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
