# Generated by Django 3.2 on 2023-08-17 02:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_devtemplate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='用户编码')),
                ('name', models.CharField(max_length=128, verbose_name='用户中文名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('enabled', models.IntegerField(choices=[(1, '启用'), (0, '停用')], default=1, verbose_name='是否启用')),
            ],
        ),
        migrations.AlterField(
            model_name='devtemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bb7a9602-5e96-4f9c-b633-af8e0fbfd4fe'), editable=False, primary_key=True, serialize=False),
        ),
    ]
