# Generated by Django 3.2 on 2023-08-17 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20230817_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devtemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8aa67d14-0275-4238-a88d-ae49fe5a25a1'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1eb387a5-0fc1-4a86-9539-69fd963fc3a2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
