# Generated by Django 3.2 on 2023-08-18 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20230818_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Update date'),
        ),
        migrations.AlterField(
            model_name='devtemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66b76289-a58c-4027-aa23-8890ab9e6897'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3b2fbe9d-42be-4843-84ad-8af51e70aced'), editable=False, primary_key=True, serialize=False),
        ),
    ]
