# Generated by Django 3.2 on 2023-08-18 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20230818_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='devtemplate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f88a3fd1-045e-4e81-9a91-5aae4e6bf3de'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7c6d65db-04be-4336-ad3e-e2560177dc13'), editable=False, primary_key=True, serialize=False),
        ),
    ]
